package model;
// Generated Dec 29, 2016 10:50:46 AM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Favorites generated by hbm2java
 */
public class Favorites implements java.io.Serializable {

	private BigDecimal favId;
	private VelibUser velibUser;
	private Station station;

	public Favorites() {}

	public Favorites(BigDecimal favId, VelibUser velibUser, Station station) {
		this.favId = favId;
		this.velibUser = velibUser;
		this.station = station;
	}
	
	public Favorites(int favId, VelibUser velibUser, Station station) {
		this (new BigDecimal(favId), velibUser, station);
	}

	public BigDecimal getFavId() {
		return this.favId;
	}

	public void setFavId(BigDecimal favId) {
		this.favId = favId;
	}

	public VelibUser getVelibUser() {
		return this.velibUser;
	}

	public void setVelibUser(VelibUser velibUser) {
		this.velibUser = velibUser;
	}

	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	@Override
	public String toString() {
		return "Favorites [favId=" + favId + ", velibUser=" 
	+ velibUser.getNom() + ", station=" + station.getStName() + "]";
	}

	
}
