package model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Station generated by hbm2java
 */
public class Station implements java.io.Serializable {

	private BigDecimal stationId;
	private String stName;
	private String address;
	private String fullAddress;
	private BigDecimal longitude;
	private BigDecimal lattitude;
	private BigDecimal stOpen;
	private BigDecimal stBonus;
	private Date updateDate;

	public Station() {}

	public Station(BigDecimal stationId, String stName, String address, String fullAddress, BigDecimal longitude,
			BigDecimal lattitude, BigDecimal stOpen, BigDecimal stBonus, Date updateDate) {
		this.stationId = stationId;
		this.stName = stName;
		this.address = address;
		this.fullAddress = fullAddress;
		this.longitude = longitude;
		this.lattitude = lattitude;
		this.stOpen = stOpen;
		this.stBonus = stBonus;
		this.updateDate = updateDate;
	}

	public Station(int stationId, String stName, String address, 
			String fullAddress, double longitude, double lattitude, int stOpen,
			int stBonus, Date updateDate) {
		this (new BigDecimal(stationId), stName, address, fullAddress, 
				new BigDecimal(longitude), new BigDecimal(lattitude), 
				new BigDecimal(stOpen), new BigDecimal(stBonus), updateDate);
	}

	public BigDecimal getStationId() {
		return this.stationId;
	}

	public void setStationId(BigDecimal stationId) {
		this.stationId = stationId;
	}

	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getFullAddress() {
		return this.fullAddress;
	}

	public void setFullAddress(String fullAddress) {
		this.fullAddress = fullAddress;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(BigDecimal lattitude) {
		this.lattitude = lattitude;
	}

	public BigDecimal getStOpen() {
		return this.stOpen;
	}

	public void setStOpen(BigDecimal stOpen) {
		this.stOpen = stOpen;
	}

	public BigDecimal getStBonus() {
		return this.stBonus;
	}

	public void setStBonus(BigDecimal stBonus) {
		this.stBonus = stBonus;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Override
	public String toString() {
		return "Station [stationId=" + stationId + ", stName=" + stName + ", address=" + address + ", fullAddress="
				+ fullAddress + ", longitude=" + longitude + ", lattitude=" + lattitude + ", stOpen=" + stOpen
				+ ", stBonus=" + stBonus + ", updateDate=" + updateDate + "]";
	}

	
}
