package model;

import java.math.BigDecimal;

/**
 * VelibUser generated by hbm2java
 */
public class VelibUser implements java.io.Serializable {

	private BigDecimal numInd;
	private String nom;
	private String prenom;
	private String vuPassword;
	private String email;
	private BigDecimal longitude;
	private BigDecimal lattitude;

	public VelibUser() {}

	public VelibUser(BigDecimal numInd, String nom, String prenom, String vuPassword, String email,
			BigDecimal longitude, BigDecimal lattitude) {
		this.numInd = numInd;
		this.nom = nom;
		this.prenom = prenom;
		this.vuPassword = vuPassword;
		this.email = email;
		this.longitude = longitude;
		this.lattitude = lattitude;
	}

	public VelibUser(int numInd, String nom, String prenom, String vuPassword, String email,
			double longitude, double lattitude) {
		this(new BigDecimal(numInd), nom, prenom, vuPassword, email, 
				new BigDecimal(longitude), new BigDecimal(lattitude));
	}

	public BigDecimal getNumInd() {
		return this.numInd;
	}

	public void setNumInd(BigDecimal numInd) {
		this.numInd = numInd;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getVuPassword() {
		return this.vuPassword;
	}

	public void setVuPassword(String vuPassword) {
		this.vuPassword = vuPassword;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(BigDecimal lattitude) {
		this.lattitude = lattitude;
	}

}
